### ISSUE TITLE
what's wrong ?

### ISSUE THREAD

**Issue by ielyanov** [Edofre/laravel-slider-pro#6]
Hi.
php composer.phar require edofre/laravel-slider-pro "v1.0.3"

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for edofre/laravel-slider-pro 1.0.3 -> satisfiable by
 edofre/laravel-slider-pro[V1.0.3].
    - edofre/laravel-slider-pro V1.0.3 requires npm-asset/slider-pro 1.3.0 -> no
 matching package found.

**Comment by Edofre** [comment]
Apparently slider-pro 1.3.0 does not longer exist, working on a fix now.

**Comment by Edofre** [comment]
@ielyanov 

This is fixed in version V1.0.4

**Comment by ielyanov** [comment]
ok. thank you
